version: '3'

services:
  chrome:
    image: browserless/chrome:latest
    ports:
    - "3000:3000"
    environment: 
    - MAX_CONCURRENT_SESSIONS=10
    - DEBUG=browserless/chrome
  webjmmy:
    image: nginx
    volumes:
    - ./static:/usr/share/nginx/html
    ports:
    - "8080:80"